name: Deploy 🚀

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    name: 🧪 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci --legacy-peer-deps

      - name: 🔍 Format
        run: npm run format

  eslint:
    name: ✅ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci --legacy-peer-deps

      - name: 🪄 Lint
        run: npm run lint

  jest:
    name: 🃏 Jest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci --legacy-peer-deps

      # ! uncomment this after you add test
      # - name: 🔬 Test
      # run: npm run test:ci
